---
  - name: Check Python Inventory
    hosts: test
    #become: true
    gather_facts: true
    #We will need to add community.general.mail not sure whether it is community.general or community.mail


    tasks:
    # Copy the required resources
      - name: Create a directory
        ansible.builtin.file:
          path: /home/hinceanb/python-scripts
          state: directory
      - name: Run pip command and create output file
        ansible.builtin.command:
          cmd: "python3 -m pip list --format json"
        register: myshell_output
      - name: copy the output to a local file
        copy:
          content: "{{ myshell_output.stdout }}"
          dest: "/home/hinceanb/python-scripts/output.json"
      - name: copy the python script
        ansible.builtin.copy:
          src: /home/hinceanb/git/python/check-packages.py
          dest: /home/hinceanb/python-scripts
      - name: Run the python script
        ansible.builtin.script:
          chdir: /home/hinceanb/python/scripts
          cmd: /home/hinceanb/git/python/check-packages.py
          executable: python3
          
         

      
  
