---
  - name: Check Python Inventory
    hosts: all
    # become: true
    gather_facts: true
    #We will need to add community.general.mail not sure whether it is community.general or community.mail


    tasks:
    # Copy the required resources
      - name: Create a directory
        ansible.builtin.command:
          cmd: "mkdir python-scripts"
      - name: Run pip command and create output file
        ansible.builtin.command:
          cmd: "python3 -m pip list --format json >> /home/hinceanb/python-scripts/output.json"
      - name: execute script
        ansble.builtin.script: 
          cmd: "{{ lookup('file', 'check-packages.py') }}"
        register: python_output

      - debug:
          msg: python_output
