---
  - name: Check Python Inventory
    hosts: all
    # become: true
    gather_facts: true
    #We will need to add community.general.mail not sure whether it is community.general or community.mail


    tasks:
    # Copy the required resources
      - name: Create a directory
        ansible.builtin.file:
          path: /home/hinceanb/python-scripts
          state: directory
      - name: Run pip command and create output file
        ansible.builtin.command:
          shell: "python3 -m pip list --format json"
        register: myshell_output
      - name: copy the output to a local file
        copy:
          content: "{{ myshell_output.stdout }}"
          dest: "/home/hinceanb/python-scripts/output.json"
  
