  - name: Get dirs to check date 
    hosts: localhost
    #become: true
    become_user: root
    gather_facts: true


    pre_tasks:
      - name: Include the file containing the users to be added
        include_vars: users.yml

    tasks:
      - name: make a list of dirs
        ansible.builtin.stat:
          path: "keys/{{ item.username }}.pub"
        with_items: "{{ users_list }}"
        register: stat_result

      - set_fact:
          dates: "{{ dates | default([]) + [{ 'time': item.stat.mtime, 
          'name': item.stat.path | replace ('.pub', '')| split ('/') | last }] }}"
        with_items: "{{ stat_result.results }}"

      - local_action: copy content={{ dates }} dest=dates/dates.yml

        #| split('\').1 | replace('.pub', '') }} " }
       

      - name: Display the Dictionary
        debug: var=dates
        #----------------JSON------------------------------
        #- debug:
        #  var: "stat_result.results[{{ item }}].stat.mtime"
        #with_sequence: start=0 end=1
        

      - name: Sending Emails to users whose keys need rotation
        community.general.mail:
          host: smtp.expersoft.site
          port: 25
          # This SMTP server does not require authentication, emails will be sent by this:
          from: administrator@ {{ ansible_hostname }}
          to: item.1.email
          #cc: Charlie Root <root@localhost> #Repository administartor should be copied here.
          subject: "Warning: SSH Key Rotation Required"
          body: Hello, this is an automatic email from System {{ ansible_hostname}}. Please generate a new SSH key-pair, following the instruction <link>. Access to the remove machines will be lost in one week. 
          charset: utf8
        delegate_to: localhost
        #debug:
          #var: item.1.username #will have to be changed to .email
        #var: item.time + 31556926  #send email here when condition 
        when:  item.0.time <= (item.0.time + 31556926) #will need to be reversed, <= for testing purposes
        #with_items: "{{ dates }}"
        loop: "{{ dates | zip (users_list) | list }}"
    
