  - name: Inpect date of public key modification and notify state=present users   
    hosts: localhost
    #become: true
    become_user: root
    gather_facts: true


    pre_tasks:
      - name: Include the file containing the users to be added
        include_vars: users.yml

    tasks:
      - name: List of keys of present users
        ansible.builtin.stat:
          path: "keys/{{ item.username }}.pub"
        with_items: "{{ users_list}}"
        register: stat_result


      - set_fact:
          dates: "{{ dates | default([]) + [{ 'time': item.stat.mtime , 
         'name': item.stat.path | replace ('.pub', '')| split ('/') | last  }] }}"
        with_items: "{{ stat_result.results }}"
        when:  item.stat.exists
 

      - local_action: copy content={{ dates }} dest=dates/dates.yml

        #- name: Display the Dictionary
        #debug: var=dates
        #
      - debug:
          var: stat_result
        #
        #
        #----------------JSON------------------------------
        #
        #
        # - debug:
        # var: "stat_result.results[{{ item }}].stat.mtime"
        #with_sequence: start=0 end=2

        # - debug:
        #  var: "stat_result.results[1].skipped "
        #with_sequence: start=0 end=2

        

      - name: Sending Emails to state=present users whose keys need rotation
        community.general.mail:
          host: smtp.expersoft.site
          port: 25
          # This SMTP server does not require authentication, emails will be sent by this:
          from: administrator@ {{ ansible_hostname }}
          to: "{{ item.1.email }}"
          #cc: Charlie Root <root@localhost> #Repository administartor should be copied here.
          subject: "Warning: SSH Key Rotation is Required for {{ item.1.username }}"
          #body: Hello, this is an automatic email from System {{ ansible_hostname}}. Please generate a new SSH key-pair, following the instruction <link>. Access to the remove machines will be lost in one week. 
          body: "{{ lookup('file', 'email.html') }}"
          charset: utf8
          subtype: html
        delegate_to: localhost
        #debug:
          #var: item.1.username #will have to be changed to .email
        #var: item.time + 31556926  #send email here when condition 
        when: item.1.state =='present' and item.0.time <= (item.0.time + 31556926) #will need to be reversed, <= for testing purposes
        #with_items: "{{ dates }}"
        loop: "{{ dates | zip (users_list) | list }}"
