- name: Say Hello to Windows
  hosts: all
  #become: true
  become_user: root
  gather_facts: true

  tasks:
    - name: Saying hello to Windows Machine
      debug: 
        msg: "Hello Windows"
      
