#- name: Say Hello to Windows
#  hosts: all
#  #become: true
#  become_user: root
#  gather_facts: true

#  tasks:
#    - name: Saying hello to Windows Machine
#      debug: 
#        msg: "Hello Windows"

---
- name: Install Telnet and check SQL
  hosts: all
  gather_facts: no
    
  tasks:
   - vars:
       ansible_python_interpreter: /usr/local/lib/python3.6/site-packages/winrm
   - name: Check SQL Server is Installed
     win_service:
       name: MSSQLSERVER
     register: sqlstatus
   - name: Start SQL Service
     win_service:
       name: MSSQLSERVER
       start_mode: auto
       state: started
     when: sqlstatus.exists
      
