#- name: Say Hello to Windows
#  hosts: all
#  #become: true
#  become_user: root
#  gather_facts: true

#  tasks:
#    - name: Saying hello to Windows Machine
#      debug: 
#        msg: "Hello Windows"

---
- name: Install Telnet and check SQL
  hosts: all
  gather_facts: no
  #dependencies:
    #galaxy: requirements.yml
    #python: requirements.txt
  vars:
    ansible_python_interpreter: /usr/bin/python3.9
    
  tasks:
   - name: Check SQL Server is Installed
     win_service:
       name: MSSQLSERVER
     register: sqlstatus
   - name: Start SQL Service
     win_service:
       name: MSSQLSERVER
       start_mode: auto
       state: started
     when: sqlstatus.exists
      
