---

    #We will need to add community.general.mail not sure whether it is community.general or community.mail
collections:
  - name: ansible.utils
  - name: ansible.posix
  - name: ansible.windows
community.general.python_requirements_info:
  dependencies:
      - pywinrm
 
  #- name: community.general

