---
- name: Install TMUX if not already present
    hosts: all
    become: true
    #become_user: root
    gather_facts: true
    collections:
      - ansible.posix

    tasks:
    #Installing tmux package if necessary
      - name: Installing tmux package if not present
          ansible.builtin.dnf:
            name: tmux
            state: present
    
